name: Release DaDa_OLED Library

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Package source files
        run: |
          zip -r DaDa_OLED.zip *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: DaDa_OLED.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
